#
#	/* DTV/USB/OTT Params CFG */
#
[AudioMode]
#audio_mode: 0-standard, 1-music, 2-movie, 3-news, 4-user
audio_mode = 0
#custom_mode_gain: band1_gain, band2_gain, ..., band7_gain
#?~?
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
#-12db ~ 12db(0 ~ 100), -6db ~ 6db(25 ~ 75)
###### Internal use only
user_mode_gain_max = 100
user_mode_gain_min = 0
user_mode_gain_min_db = -12
######

#
#	/* ATV Params CFG */
#
[ATV AudioMode]
audio_mode = 0
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
######

#
#	/* CVBS1 Params CFG */
#
[CVBS1 AudioMode]
audio_mode = 0
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
######

#
#	/* CVBS2 Params CFG */
#
[CVBS2 AudioMode]
audio_mode = 0
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
######

#
#	/* HDMI1 Params CFG */
#
[HDMI1 AudioMode]
audio_mode = 0
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
######

#
#	/* HDMI2 Params CFG */
#
[HDMI2 AudioMode]
audio_mode = 0
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
######

#
#	/* HDMI3 Params CFG */
#
[HDMI3 AudioMode]
audio_mode = 0
standard_mode_gain = 50,50,50,50,50,50,50
music_mode_gain = 75,50,60,75,75,50,50
movie_mode_gain = 85,85,80,45,40,75,85
news_mode_gain = 35,35,35,55,55,35,35
user_mode_gain = 50,50,50,50,50,50,50
spk_delay = 0
owa_delay = 0
spk_delay_offset = 0
owa_delay_offset = 0
######

[Volume]
#volume_index:0~100
###### Internal use only
volume_index = 5
speaker_volume = 60
headphone_volume = 60
owa_volume = 100
arc_volume = 100
a2dp_volume = 100
spk_mute = 0
headphone_mute = 0
owa_mute = 0
arc_mute = 0
a2dp_mute = 0
speaker_max = -38
headphone_max = -38
owa_max = 0
arc_max = 0
a2dp_max = -38
######

#volume_curve:-512~120
volume_curve[00]=-512,
volume_curve[10]=-164,-162,-160,-158,-156,-154,-152,-150,-148,-146,
volume_curve[20]=-144,-142,-140,-138,-136,-134,-132,-130,-128,-126,
volume_curve[30]=-124,-122,-120,-118,-116,-114,-112,-110,-109,-108,
volume_curve[40]=-107,-106,-105,-104,-103,-102,-101,-100,-99,-98,
volume_curve[50]=-97,-96,-95,-94,-93,-92,-91,-90,-89,-88,
volume_curve[60]=-87,-86,-85,-84,-83,-82,-81,-80,-79,-78,
volume_curve[70]=-77,-76,-75,-74,-73,-72,-71,-70,-69,-68,
volume_curve[80]=-67,-66,-65,-64,-63,-62,-61,-60,-59,-58,
volume_curve[90]=-57,-56,-55,-54,-53,-52,-51,-50,-49,-48,
volume_curve[100]=-47,-46,-45,-44,-43,-42,-41,-40,-39,-38,

[Peq]
peq1_freq = 1,10,10,10,10
peq2_freq = 1,10,10,10,10
peq1_q = 2,2,2,0,0
peq2_q = 0,0,2,2,2
peq1_gain = 0,0,0,0,0
peq2_gain = 0,0,0,0,0
peq_overall_gain = 0
peq_mode = 0

[Prescale]
#prescale: ?~?
atv_prescale = 32
hdmi_prescale = 32
av_prescale = 32
usb_prescale = 32

[Drc]
#threshold:-32~12
#decay:5~14
speaker_drc_enable = 0
speaker_drc_threshold = 12
speaker_drc_decay = 5
headphone_drc_enable = 0
headphone_drc_threshold = 12
headphone_drc_decay = 5

[Avc]
avc_gain = 3
avc_threshold = 0
avc_limit = 0
avc_decay_time = 1

[OutGain]
speaker_gain = 26
headphone_gain = 7
owa_gain = 0

[Balance]
speaker_balance = 0
headphone_balance = 0

[Other]
avc_mode = 0
surround_mode = 0
atv_mts_out_mode = 0

###########################
#       Audio ??????      #
###########################

