##############
#Example:
#        ResolutionType[0/n]=\
#        CropLeft,CropRight,CropUp,CropDown        FULL     0
#        CropLeft,CropRight,CropUp,CropDown        16x9     1
#        CropLeft,CropRight,CropUp,CropDown        4x3      2
#        CropLeft,CropRight,CropUp,CropDown        Cinema   3
#        CropLeft,CropRight,CropUp,CropDown        Zoom     4
#        CropLeft,CropRight,CropUp,CropDown        Auto     5
#        CropLeft,CropRight,CropUp,CropDown        DotByDot 6
##############

##############
#ATVOverscanSetting:ResolutionType[x/0]
# 0:   SIG_NTSC
# 1:   SIG_NTSC443
# 2:   SIG_SECAM
# 3:   SIG_PAL
# 4:   SIG_PALM
# 5:   SIG_PALNC
# 6:   SIG_PAL60
##############
[ATVOverscanSetting]
ResolutionType[0/0]=0,0,0,0,\
ResolutionType[0/1]=17,22,10,8,\
ResolutionType[0/2]=25,25,25,25,\
ResolutionType[0/3]=25,25,25,25,\
ResolutionType[0/4]=125,125,125,125,\
ResolutionType[0/5]=0,0,0,0,\
ResolutionType[0/6]=0,0,0,0,\

ResolutionType[1/0]=0,0,0,0,\
ResolutionType[1/1]=17,22,10,8,\
ResolutionType[1/2]=25,25,25,25,\
ResolutionType[1/3]=25,25,25,25,\
ResolutionType[1/4]=125,125,125,125,\
ResolutionType[1/5]=0,0,0,0,\
ResolutionType[1/6]=0,0,0,0,\

ResolutionType[2/0]=0,0,0,0,\
ResolutionType[2/1]=9,41,18,28,\
ResolutionType[2/2]=15,15,15,15,\
ResolutionType[2/3]=15,15,15,15,\
ResolutionType[2/4]=125,125,125,125,\
ResolutionType[2/5]=0,0,0,0,\
ResolutionType[2/6]=0,0,0,0,\

ResolutionType[3/0]=0,0,0,0,\
ResolutionType[3/1]=27,25,12,12,\
ResolutionType[3/2]=25,25,25,25,\
ResolutionType[3/3]=25,25,25,25,\
ResolutionType[3/4]=125,125,125,125,\
ResolutionType[3/5]=0,0,0,0,\
ResolutionType[3/6]=0,0,0,0,\

ResolutionType[4/0]=0,0,0,0,\
ResolutionType[4/1]=27,25,12,12,\
ResolutionType[4/2]=25,25,25,25,\
ResolutionType[4/3]=25,25,25,25,\
ResolutionType[4/4]=125,125,125,125,\

ResolutionType[5/0]=0,0,0,0,\
ResolutionType[5/1]=27,25,12,12,\
ResolutionType[5/2]=25,25,25,25,\
ResolutionType[5/3]=25,25,25,25,\
ResolutionType[5/4]=125,125,125,125,\

ResolutionType[6/0]=0,0,0,0,\
ResolutionType[6/1]=27,25,12,12,\
ResolutionType[6/2]=25,25,25,25,\
ResolutionType[6/3]=25,25,25,25,\
ResolutionType[6/4]=125,125,125,125,\


##############
#DTVOverscanSetting:ResolutionType[x]
# 0:    DTV_480I
# 1:    DTV_480P
# 2:    DTV_576I
# 3:    DTV_576P
# 4:    DTV_720P
# 5:    DTV_1080I
# 6:    DTV_1080P
##############
[DTVOverscanSetting]
ResolutionType[0/0]=0,0,0,0,\
ResolutionType[0/1]=0,0,0,0,\
ResolutionType[0/2]=0,0,0,0,\
ResolutionType[0/3]=0,0,0,0,\
ResolutionType[0/4]=0,0,0,0,\
ResolutionType[0/5]=0,0,0,0,\
ResolutionType[0/6]=0,0,0,0,\

ResolutionType[1/0]=0,0,0,0,\
ResolutionType[1/1]=0,0,0,0,\
ResolutionType[1/2]=0,0,0,0,\
ResolutionType[1/3]=0,0,0,0,\
ResolutionType[1/4]=0,0,0,0,\
ResolutionType[1/5]=0,0,0,0,\
ResolutionType[1/6]=0,0,0,0,\

ResolutionType[2/0]=0,0,0,0,\
ResolutionType[2/1]=0,0,0,0,\
ResolutionType[2/2]=0,0,0,0,\
ResolutionType[2/3]=0,0,0,0,\
ResolutionType[2/4]=0,0,0,0,\
ResolutionType[2/5]=0,0,0,0,\
ResolutionType[2/6]=0,0,0,0,\

ResolutionType[3/0]=0,0,0,0,\
ResolutionType[3/1]=0,0,0,0,\
ResolutionType[3/2]=0,0,0,0,\
ResolutionType[3/3]=0,0,0,0,\
ResolutionType[3/4]=0,0,0,0,\
ResolutionType[3/5]=0,0,0,0,\
ResolutionType[3/6]=0,0,0,0,\

ResolutionType[4/0]=0,0,0,0,\
ResolutionType[4/1]=0,0,0,0,\
ResolutionType[4/2]=0,0,0,0,\
ResolutionType[4/3]=0,0,0,0,\
ResolutionType[4/4]=0,0,0,0,\

ResolutionType[5/0]=0,0,0,0,\
ResolutionType[5/1]=0,0,0,0,\
ResolutionType[5/2]=0,0,0,0,\
ResolutionType[5/3]=0,0,0,0,\
ResolutionType[5/4]=0,0,0,0,\

ResolutionType[6/0]=0,0,0,0,\
ResolutionType[6/1]=0,0,0,0,\
ResolutionType[6/2]=0,0,0,0,\
ResolutionType[6/3]=0,0,0,0,\
ResolutionType[6/4]=0,0,0,0,\

##############
#HDMIOverscanSetting:ResolutionType[x]
# 0:     HDMI_REZ_480I
# 1:     HDMI_REZ_480P
# 2:     HDMI_REZ_576I
# 3:     HDMI_REZ_576P
# 4:     HDMI_REZ_720P
# 5:     HDMI_REZ_1080I
# 6:     HDMI_REZ_1080P
# 7:     HDMI_REZ_960P
# 8:     HDMI_REZ_2160P3840
# 9:     HDMI_REZ_2160P4096
# 10:     HDMI_REZ_PC_640_480
# 11:     HDMI_REZ_PC_720_400
# 12:     HDMI_REZ_PC_800_600
# 13:     HDMI_REZ_PC_1024_768
# 14:     HDMI_REZ_PC_1152_864
# 15:     HDMI_REZ_PC_1280_720
# 16:     HDMI_REZ_PC_1280_768
# 17:     HDMI_REZ_PC_1280_800
# 18:     HDMI_REZ_PC_1280_960
# 19:     HDMI_REZ_PC_1280_1024
# 20:     HDMI_REZ_PC_1360_768
# 21:     HDMI_REZ_PC_1366_768
# 22:     HDMI_REZ_PC_1440_900
# 23:     HDMI_REZ_PC_1400_1050
# 24:     HDMI_REZ_PC_1920_1080
# 25:     HDMI_REZ_PC_3840_2160
# 26:     HDMI_REZ_PC_4096_2160
##############
[HDMIOverscanSetting]
ResolutionType[0/0]=0,0,0,0,\
ResolutionType[0/1]=15,15,15,15,\
ResolutionType[0/2]=15,15,15,15,\
ResolutionType[0/3]=15,15,15,15,\
ResolutionType[0/4]=125,125,125,125,\
ResolutionType[0/5]=0,0,0,0,\
ResolutionType[0/6]=0,0,0,0,\

ResolutionType[1/0]=0,0,0,0,\
ResolutionType[1/1]=15,15,15,15,\
ResolutionType[1/2]=15,15,15,15,\
ResolutionType[1/3]=15,15,15,15,\
ResolutionType[1/4]=125,125,125,125,\
ResolutionType[1/5]=0,0,0,0,\
ResolutionType[1/6]=0,0,0,0,\

ResolutionType[2/0]=0,0,0,0,\
ResolutionType[2/1]=15,15,15,15,\
ResolutionType[2/2]=15,15,15,15,\
ResolutionType[2/3]=15,15,15,15,\
ResolutionType[2/4]=125,125,125,125,\
ResolutionType[2/5]=0,0,0,0,\
ResolutionType[2/6]=0,0,0,0,\

ResolutionType[3/0]=0,0,0,0,\
ResolutionType[3/1]=15,15,15,15,\
ResolutionType[3/2]=15,15,15,15,\
ResolutionType[3/3]=15,15,15,15,\
ResolutionType[3/4]=125,125,125,125,\
ResolutionType[3/5]=0,0,0,0,\
ResolutionType[3/6]=0,0,0,0,\

ResolutionType[4/0]=0,0,0,0,\
ResolutionType[4/1]=15,15,15,15,\
ResolutionType[4/2]=15,15,15,15,\
ResolutionType[4/3]=15,15,15,15,\
ResolutionType[4/4]=125,125,125,125,\

ResolutionType[5/0]=0,0,0,0,\
ResolutionType[5/1]=15,15,15,15,\
ResolutionType[5/2]=15,15,15,15,\
ResolutionType[5/3]=15,15,15,15,\
ResolutionType[5/4]=125,125,125,125,\

ResolutionType[6/0]=0,0,0,0,\
ResolutionType[6/1]=15,15,15,15,\
ResolutionType[6/2]=15,15,15,15,\
ResolutionType[6/3]=15,15,15,15,\
ResolutionType[6/4]=125,125,125,125,\

ResolutionType[7/0]=0,0,0,0,\
ResolutionType[7/1]=15,15,15,15,\
ResolutionType[7/2]=15,15,15,15,\
ResolutionType[7/3]=15,15,15,15,\
ResolutionType[7/4]=125,125,125,125,\

ResolutionType[8/0]=0,0,0,0,\
ResolutionType[8/1]=0,0,0,0,\
ResolutionType[8/2]=0,0,0,0,\
ResolutionType[8/3]=0,0,0,0,\
ResolutionType[8/4]=125,125,125,125,\

ResolutionType[9/0]=0,0,0,0,\
ResolutionType[9/1]=0,0,0,0,\
ResolutionType[9/2]=0,0,0,0,\
ResolutionType[9/3]=0,0,0,0,\
ResolutionType[9/4]=125,125,125,125,\

ResolutionType[10/0]=0,0,0,0,\
ResolutionType[10/1]=0,0,0,0,\
ResolutionType[10/2]=0,0,0,0,\
ResolutionType[10/3]=0,0,0,0,\
ResolutionType[10/4]=125,125,125,125,\

ResolutionType[11/0]=0,0,0,0,\
ResolutionType[11/1]=0,0,0,0,\
ResolutionType[11/2]=0,0,0,0,\
ResolutionType[11/3]=0,0,0,0,\
ResolutionType[11/4]=125,125,125,125,\

ResolutionType[12/0]=0,0,0,0,\
ResolutionType[12/1]=0,0,0,0,\
ResolutionType[12/2]=0,0,0,0,\
ResolutionType[12/3]=0,0,0,0,\
ResolutionType[12/4]=125,125,125,125,\

ResolutionType[13/0]=0,0,0,0,\
ResolutionType[13/1]=0,0,0,0,\
ResolutionType[13/2]=0,0,0,0,\
ResolutionType[13/3]=0,0,0,0,\
ResolutionType[13/4]=125,125,125,125,\

ResolutionType[14/0]=0,0,0,0,\
ResolutionType[14/1]=0,0,0,0,\
ResolutionType[14/2]=0,0,0,0,\
ResolutionType[14/3]=0,0,0,0,\
ResolutionType[14/4]=125,125,125,125,\

ResolutionType[15/0]=0,0,0,0,\
ResolutionType[15/1]=0,0,0,0,\
ResolutionType[15/2]=0,0,0,0,\
ResolutionType[15/3]=0,0,0,0,\
ResolutionType[15/4]=125,125,125,125,\

ResolutionType[16/0]=0,0,0,0,\
ResolutionType[16/1]=0,0,0,0,\
ResolutionType[16/2]=0,0,0,0,\
ResolutionType[16/3]=0,0,0,0,\
ResolutionType[16/4]=125,125,125,125,\

ResolutionType[17/0]=0,0,0,0,\
ResolutionType[17/1]=0,0,0,0,\
ResolutionType[17/2]=0,0,0,0,\
ResolutionType[17/3]=0,0,0,0,\
ResolutionType[17/4]=125,125,125,125,\

ResolutionType[18/0]=0,0,0,0,\
ResolutionType[18/1]=0,0,0,0,\
ResolutionType[18/2]=0,0,0,0,\
ResolutionType[18/3]=0,0,0,0,\
ResolutionType[18/4]=125,125,125,125,\

ResolutionType[19/0]=0,0,0,0,\
ResolutionType[19/1]=0,0,0,0,\
ResolutionType[19/2]=0,0,0,0,\
ResolutionType[19/3]=0,0,0,0,\
ResolutionType[19/4]=125,125,125,125,\

ResolutionType[20/0]=0,0,0,0,\
ResolutionType[20/1]=0,0,0,0,\
ResolutionType[20/2]=0,0,0,0,\
ResolutionType[20/3]=0,0,0,0,\
ResolutionType[20/4]=125,125,125,125,\

ResolutionType[21/0]=0,0,0,0,\
ResolutionType[21/1]=0,0,0,0,\
ResolutionType[21/2]=0,0,0,0,\
ResolutionType[21/3]=0,0,0,0,\
ResolutionType[21/4]=125,125,125,125,\

ResolutionType[22/0]=0,0,0,0,\
ResolutionType[22/1]=0,0,0,0,\
ResolutionType[22/2]=0,0,0,0,\
ResolutionType[22/3]=0,0,0,0,\
ResolutionType[22/4]=125,125,125,125,\

ResolutionType[23/0]=0,0,0,0,\
ResolutionType[23/1]=0,0,0,0,\
ResolutionType[23/2]=0,0,0,0,\
ResolutionType[23/3]=0,0,0,0,\
ResolutionType[23/4]=125,125,125,125,\

ResolutionType[24/0]=0,0,0,0,\
ResolutionType[24/1]=0,0,0,0,\
ResolutionType[24/2]=0,0,0,0,\
ResolutionType[24/3]=0,0,0,0,\
ResolutionType[24/4]=125,125,125,125,\

ResolutionType[25/0]=0,0,0,0,\
ResolutionType[25/1]=0,0,0,0,\
ResolutionType[25/2]=0,0,0,0,\
ResolutionType[25/3]=0,0,0,0,\
ResolutionType[25/4]=125,125,125,125,\

ResolutionType[26/0]=0,0,0,0,\
ResolutionType[26/1]=0,0,0,0,\
ResolutionType[26/2]=0,0,0,0,\
ResolutionType[26/3]=0,0,0,0,\
ResolutionType[26/4]=125,125,125,125,\

##############
#CVBSOverscanSetting:ResolutionType[x/0]
# 0:   SIG_NTSC
# 1:   SIG_NTSC443
# 2:   SIG_SECAM
# 3:   SIG_PAL
# 4:   SIG_PALM
# 5:   SIG_PALNC
# 6:   SIG_PAL60
##############
[CVBSOverscanSetting]
ResolutionType[0/0]=0,0,0,0,\
ResolutionType[0/1]=17,22,25,25,\
ResolutionType[0/2]=25,25,25,25,\
ResolutionType[0/3]=25,25,25,25,\
ResolutionType[0/4]=125,125,125,125,\
ResolutionType[0/5]=0,0,0,0,\
ResolutionType[0/6]=0,0,0,0,\

ResolutionType[1/0]=0,0,0,0,\
ResolutionType[1/1]=17,22,25,25,\
ResolutionType[1/2]=25,25,25,25,\
ResolutionType[1/3]=25,25,25,25,\
ResolutionType[1/4]=125,125,125,125,\
ResolutionType[1/5]=0,0,0,0,\
ResolutionType[1/6]=0,0,0,0,\

ResolutionType[2/0]=0,0,0,0,\
ResolutionType[2/1]=9,41,25,25,\
ResolutionType[2/2]=25,25,25,25,\
ResolutionType[2/3]=25,25,25,25,\
ResolutionType[2/4]=125,125,125,125,\
ResolutionType[2/5]=0,0,0,0,\
ResolutionType[2/6]=0,0,0,0,\

ResolutionType[3/0]=0,0,0,0,\
ResolutionType[3/1]=27,25,25,25,\
ResolutionType[3/2]=25,25,25,25,\
ResolutionType[3/3]=25,25,25,25,\
ResolutionType[3/4]=125,125,125,125,\
ResolutionType[3/5]=0,0,0,0,\
ResolutionType[3/6]=0,0,0,0,\

ResolutionType[4/0]=0,0,0,0,\
ResolutionType[4/1]=27,25,25,25,\
ResolutionType[4/2]=25,25,25,25,\
ResolutionType[4/3]=25,25,25,25,\
ResolutionType[4/4]=125,125,125,125,\

ResolutionType[5/0]=0,0,0,0,\
ResolutionType[5/1]=27,25,25,25,\
ResolutionType[5/2]=25,25,25,25,\
ResolutionType[5/3]=25,25,25,25,\
ResolutionType[5/4]=125,125,125,125,\

ResolutionType[6/0]=0,0,0,0,\
ResolutionType[6/1]=27,25,25,25,\
ResolutionType[6/2]=25,25,25,25,\
ResolutionType[6/3]=25,25,25,25,\
ResolutionType[6/4]=125,125,125,125,\
