# example
# Dummy module config, just for test.
[module]
bus_type           = 0x1
device_id          = 0x000018F0
module_name        = dummy
driver_name        = dummy
driver_module_name = dummy
vendor_name        = allwinnertech
bt_support         = 0

# override xr819
[module]
bus_type           = 0x1
device_id          = 0x00202281
module_name        = xr819s
driver_name        = xr819
driver_module_name = xr819
vendor_name        = xradio
bt_support         = 1
